### ISSUE TITLE
add annotation to elector Pods

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/k8s-elector#19]
related discussion: https://github.com/vapor-ware/vapor-charts/pull/235#discussion_r327162492

I think something like:

* for leader: `io.vapor.elector/status=leader`
* for standby: `io.vapor.elector/status=standby`

@lazypower do the above annotations seem okay to you?

**Comment by lazypower** [comment]
Is the k8s-elector image open source? if so, we should probably not limit to the io.vapor namespace and instead use something more akin to the project name

`k8s.elector/status`

or `k8s-elector/status` both make sense to me.
